fix minor bug: export const hasAccessOrPublished: 2024-02-07T15:22:37.824164075Z stdout F src/access/roles.ts(10,54): error TS2339: Property 'reg' does not exist on type 'AccessArgs<any, User>'.